name: Deploy Restaurant Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Deploy directly from the root directory

    - name: Set environment variables for EmailJS
      env:
        EMAILJS_SERVICE_ID: ${{ secrets.SER}}
        EMAILJS_TEMPLATE_ID: ${{ secrets.TEM }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.KEY }}
      run: echo "Environment variables for EmailJS set" 
